### ISSUE TITLE
Fatal Error when using phpSmug v3.4 as of 4/22/2016

### ISSUE THREAD

**Issue by rgjohnson** [lildude/phpSmug#32]
We have an application that is using phpSmug v 3.4 and version 1.2.2 of the SmugMug API. As of April 22nd we are getting the following error when attampting to run the application and log into SmugMug. 

"Fatal error: Cannot redeclare class HttpRequestException in /home4/sniperac/public_html/locations/TAG/includes/phpSmug/phpSmug.php on line 904"

Any ideas? Is it time to upgrade the application to use phpSmug 4 and 2.0 version of the API?

Thanks,
Ryan

**Comment by lildude** [comment]
It sounds like either your phpSmug.php file has somehow been duplicated within itself resulting in two declarations of `HttpRequestException` (first declared on https://github.com/lildude/phpSmug/blob/3.4/phpSmug.php#L904) or you've made changes to some other code in which you're pulling in phpSmug.php that is also using a `HttpRequestException` classname.

Of the two, I suspect it may be the latter, in which case the simple fix would be to change your other code or rename the class in phpSmug.

phpSmug 4 won't suffer from this problem as it now use Guzzle for the HTTP requests rather than including it's own request code.

**Comment by lildude** [comment]
All quiet after several months, so I'm closing this. Feel free to re-open if you continue to hit this issue.
