### ISSUE TITLE
Debugging 400 response

### ISSUE THREAD

**Issue by mcavag** [lildude/phpSmug#41]
Hi,

We're upgrading to the 4.0 release, and having trouble debugging a call to create an album. We get a 400 response and the 'readable' error is such:

```
Client error: `POST https://api.smugmug.com/api/v2/folder/user/[username]!albums` resulted in a `400 Bad Request` response:
{"Options":{"Methods":["POST"],"ParameterDescription":{"Varchar":"Variable length text from MIN_CHARS to MAX_CHARS (MAX_ (truncated...)
```

I suspect something is wrong with my request, but not sure what exactly.

Does SmugMug's API provide a "Here's exactly what's wrong with your request" message that we can access, or do they just return a list of the parameters they expect at that endpoint (which is what it seems to be doing above, albeit truncated by phpSmug)?

**Comment by lildude** [comment]
> Does SmugMug's API provide a "Here's exactly what's wrong with your request" message that we can access, or do they just return a list of the parameters they expect at that endpoint (which is what it seems to be doing above, albeit truncated by phpSmug)?

Possibly. The [API docs](https://api.smugmug.com/api/v2/doc) have a wealth of info along with the [Live API Browser](https://api.smugmug.com/api/v2), though in this case I'm not sure it'll be more precise as according to the [API docs](https://api.smugmug.com/api/v2/doc/pages/concepts.html#status-codes), the 400 error code means "Your request contained invalid parameters or was otherwise invalid" so it may not be able to determine which parameter is at fault. It looks like this may be the case as it's returning what you'd get if your used `$client->options()` to query the params the endpoint takes.

Regarding the truncation, Guzzle, the library phpSmug uses for the HTTP requests, is what is truncating the response. You may find enabling debugging will get you the full response. Something like this:

```php
$options = [
  "AppName"   => "[Your app name]",
  "debug"     => true,   # This enables Guzzle's request debug output
  'OAuthSecret' => "[Your OAuthsecret]",
];

$client = new phpSmug\Client("[Your OAuth token]", $options);
$client->setToken('[your access token]', '[your access token secret]');
$response = $client->post('[path/to/new/album]', $options);
print_r($response);
```

That all said, I've seen this problem crop up when peeps JSON encode the params they're passing to methods like `$client->post()`, like in https://github.com/lildude/phpSmug/issues/37. 

Are you by any chance doing this?  If so, there's no need to. phpSmug will do it for you.

**Comment by mcavag** [comment]
I saw that other person's issue and no, we're just passing in a regular old PHP array as the $options parameter.

Thanks for your help - I wasn't able to get an un-truncated version of the response using the debug parameter for Guzzle. Looking at their source, it doesn't seem like they do any kind of conditional check based on it when truncating.

We were able to get things working by starting from zero and only passing in the minimum values needed to create an album. I've spent quite a bit of time reading through the API 2.0 docs and I expect the SmugMug API is not going to provide any useful debugging help aside from a 400 error code.
