### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by riddlemd** [lildude/phpSmug#48]
I notice you've not merged a fairly important branch change into master, are you no longer maintaining this?

**Comment by lildude** [comment]
Nope. It’s just really stable mainly because the API hasn’t changed and peeps haven’t hit many problems. Regarding that branch… I’m assuming you’re referring to the expansions branch... see my comment from yesterday https://github.com/lildude/phpSmug/issues/47#issuecomment-404037469

As for this being important… you should have brought it up sooner 😉 I have no idea what peeps are doing with phpSmug and if they’re having problems or want features if they don’t open issues. Dgrin is really quiet these days too.

**Comment by riddlemd** [comment]
Thanks for the quick reply, the branch totally makes sense to be merged in to master. Expansions make life so much easier and I did not even notice that branch existed until I forked the project to add support (which ended up being almost exactly how you coded it)
