### ISSUE TITLE
list all folders

### ISSUE THREAD

**Issue by tunes3540** [lildude/phpSmug#58]
With API 2.0 on smugmug, I can't seem to find a way to list my folders (not Albums). My library at Smugmug is all folders on top, and gallerys below them. When I list albums, I only see some of my gallerys, not all. They used to call them gallerys not albums. I've figured out how to use the new phpsmug to get those albums, and list the photos inside, I'm just missing lots of them. Almost all my gallerys are public, so I'm not authenticating when using phpsmug. Thanks for any help.

**Comment by danielmreck** [comment]
Hey there!

This is a great question, although at its core it's really a SmugMug API question that probably is best asked in the Digital Grin forum at https://dgrin.com/categories/smugmug-api-support-integrations or directly to the SmugMug API team at api@smugmug.com. This GitHub issue tracker is intended for reporting problems with phpSmug's functionality.

However, to get you started off, perhaps we can point you in the right direction.  You are correct that SmugMug's API for the _User_ endpoint doesn't have a (documented) way to list a user's folders. 

However, there is a _FolderList_ endpoint that will return a recursive list of all your folders. Here is a demonstration using SmugMug co-founder cmac's account because it already appears in the API documentation: https://api.smugmug.com/api/v2/folder/user/cmac!folderlist  (Replace 'cmac' with your own username.)

If you remove _!folderlist_ from the Uri, you can see the other data you can query from the _Folder_ endpoint: https://api.smugmug.com/api/v2/folder/user/cmac!folderlist

Please note that all the folder-related API endpoints are listed as depreciated and could disappear at anytime, which is unfortunate because they are useful.  In their absence, you would need to look up your username's Node ID and use the node-traversing endpoints. It would require many more API calls to sort through all the child nodes to find the folders, so I'm not sure why they are depreciating the useful functionality.

Regarding the missing albums, do they all appear correctly when you use the _UserAlbums_ endpoint on the live API browser?  Again, an example with cmac's data: https://api.smugmug.com/api/v2/user/cmac!albums

It may be that some of your albums are not being returned due _count_ and _start_ arguments, which control the size of returned data pages. On the live API browser, SmugMug limits responses to 10 objects per page. Of the top of my head, I'm not sure how they break up JSON responses.

Best wishes!
Daniel
