### ISSUE TITLE
Undefined Property / and Class 'phpSmug\Client' not found

### ISSUE THREAD

**Issue by mattgktw** [lildude/phpSmug#62]
Hello,

As will become painfully clear, I am not very well-versed in APIs, so please be patient with me and assume the worst (as in, does he really not know how to do that? No. No, he doesn't.)

I just started trying to use the phpSmug example code and have run into two issues:

1) Various Errors: 

_Notice: Undefined property: stdClass::$Album in /opt/bitnami/apps/wordpress/htdocs/smugmug/index2.php on line 54
Notice: Trying to get property 'Uris' of non-object in /opt/bitnami/apps/wordpress/htdocs/smugmug/index2.php on line 54
Notice: Trying to get property 'AlbumImages' of non-object in /opt/bitnami/apps/wordpress/htdocs/smugmug/index2.php on line 54
stdClass Object ( [Uri] => /api/v2/user/gktwvillage!albums?count=1 [Locator] => Album [LocatorType] => Objects [Pages] => stdClass Object ( [Total] => 0 [Start] => 1 [Count] => 0 [RequestedCount] => 1 [FirstPage] => /api/v2/user/gktwvillage!albums?count=1&start=1 [LastPage] => /api/v2/user/gktwvillage!albums?count=1&start=0 ) )
Notice: Undefined property: stdClass::$AlbumImage in /opt/bitnami/apps/wordpress/htdocs/smugmug/index2.php on line 57
Warning: Invalid argument supplied for foreach() in /opt/bitnami/apps/wordpress/htdocs/smugmug/index2.php on line 57_

2) After reading the transcript of someone else's issue on this forum, I thought that the reason for the above errors was that all of our albums were private; so, I took the answer provided to that user and attempted to use the oAuth example, where I get this error:

_Fatal error: Uncaught Error: Class 'phpSmug\Client' not found in_

Can you offer any suggestions as to how to fix this?

Thanks,
Matt

**Comment by lildude** [comment]
Yup, your first set of errors appear to be due to a lack of public access to your albums, which means you'll indeed need to use an auth method, like that in `example-oauth.php` or `example-external-links.php`.

> Fatal error: Uncaught Error: Class 'phpSmug\Client' not found in

This error suggests the phpSmug client code can't be found. The most likely causes are:

- You've not installed phpSmug, or
- You're missing this line from the top of the example: `require_once 'vendor/autoload.php';`

As an aside, you might want to try testing and setting things up completely independently of another application like Wordpress. I regularly use [VSCode Remote Containers](https://code.visualstudio.com/docs/remote/containers-tutorial) for such situations as it provides a clean reproducible environment unencumbered by other applications.  The samples in this repo work perfectly in the sample PHP container.

**Comment by mattgktw** [comment]
Hi,

Thank you. I got the example-external-links.php example to work, somewhat, I suppose. It is returning images, anyway. As for the basic example, I have the autoload line and I am assuming that phpSmug is loaded since I got the example-external-links example to work.

Thanks for the VSCode tip, I will check it out.

Matt
