### ISSUE TITLE
Saving/Reusing the Token

### ISSUE THREAD

**Issue by mattgktw** [lildude/phpSmug#65]
Hello,

I am looking at the oAuth example and trying to use this so I don't have to constantly login every time I go to a new page:

`$options = [ 
'AppName' => 'My Cool App/1.0 (http://app.com)',
                ];
                $client = new phpSmug\Client($APIKey, $options);
                $client->setToken($_SESSION['token'], $_SESSION['tokensecret']);
`
but I get this error message:

_An OAuthSecret is required for all SmugMug OAuth interactions. (Error Code: 0)_

The session variables and other variable I am using are populated.

I am sure I am missing some basic concept...I just don't know what I don't know and I have searched all over to figure it out without having to bother someone about it. Would you please let me know what I am doing wrong?

Thanks,
Matt

**Comment by lildude** [comment]
You're seeing this error because you're not passing your app's OAuthSecret.  

Compare your code (reformatted for clarity):

```php
$options = [
  'AppName' => 'My Cool App/1.0 (http://app.com)', 
]; 
$client = new phpSmug\Client($APIKey, $options);
$client->setToken($_SESSION['token'], $_SESSION['tokensecret']); 
```

... with that in the example https://github.com/lildude/phpSmug/blob/c5dc8dbdae6c90d8bea453595b1f71103bc1635e/examples/example-oauth.php#L45-L51

The client must _always_ be instantiated with `OAuthSecret` set to your app's OAuthSecret.

**Comment by mattgktw** [comment]
Ok, thank you for your time. I was following the example from https://lildude.github.io/phpSmug/#basic-usage detailed below.

_Once you’ve saved the token and token secret, you will no longer need to use any of the authentication methods above. Simply call $client->setToken(); and pass the token and secret immediately after instantiating your object instance._

_For example:_

`<?php`
`$options = [`
   ` 'AppName' => 'My Cool App/1.0 (http://app.com)',`
`];`
`$client = new phpSmug\Client('[YOUR_API_KEY]', $options));`
`$client->setToken('[OAUTH_TOKEN]', '[OAUTH_TOKEN_SECRET]');`
`$albums = $client->get('user/[YOUR_USERNAME]!albums');`

I made the change and I got a series of these errors for parameter 1 and 2:

_Warning: strpos() expects parameter 1 to be string, object given in /opt/bitnami/apps/wordpress/htdocs/smugmug/lib/phpSmug/Client.php on line 124_

I am assuming that is related to:

`$client->setToken($_SESSION['token'], $_SESSION['tokensecret']);`

Thanks, again.
Matt

**Comment by lildude** [comment]
Ah yes, that section of the docs is for unauthed access. I now see the docs in the authentication section, specifically step three at https://lildude.github.io/phpSmug/#step-3-request-the-access-token could do with a note about sending the OAuthSecret.

> _Warning: strpos() expects parameter 1 to be string, object given in /opt/bitnami/apps/wordpress/htdocs/smugmug/lib/phpSmug/Client.php on line 124_
> 
> I am assuming that is related to:
> 
> `$client->setToken($_SESSION['token'], $_SESSION['tokensecret']);`

I don't think it'll be related to that method call. The line in question is here in the code:

https://github.com/lildude/phpSmug/blob/c5dc8dbdae6c90d8bea453595b1f71103bc1635e/lib/phpSmug/Client.php#L124

... so it's probably coming from `$albums = $client->get('user/[YOUR_USERNAME]!albums');` or other similar calls.

The issue is the argument being passed in is an object but it needs to be a string.

**Comment by mattgktw** [comment]
That's good to know, thanks. I put a few echos in my code to see where the process is getting hung up; 

`$options = [`
 `                   'AppName' => 'My Cool App/1.0 (http://app.com)',`
  `                  'OAuthSecret' => $OAuthSecret, // You need to pass your OAuthSecret in order to authenticate with OAuth.`
   `             ];`
    `            $client = new phpSmug\Client($APIKey, $options);`
     `           $client->setToken($_SESSION['token'], $_SESSION['tokensecret']);`
      `      `
       `         // Get the username of the authenticated user`
        `        $username = $client->get('!authuser')->User->NickName;`
         `       // Get the first public album`
          `      $albums = $client->get("user/{$username}!albums");`
           `     // Get the first 25 photos in the album`
            `    $images = $client->get($albums->Album[0]->Uris->AlbumImages, array('count' => 25));`
            `   // Display the image thumbnails.`
            `   foreach ($images->AlbumImage as $image) {`
            `       printf('<a href="%s"><img src="%s" title="%s" alt="%s" width="150" height="150" /></a>', $image->WebUri, `` $client->signResource($image->ThumbnailUrl), $image->Title, $image->ImageKey);`
  `              } `

It looks like it is getting bogged down at:

`$images = $client->get($albums->Album[0]->Uris->AlbumImages, array('count' => 25));`

So, that's probably not phpSmug. Thank you for your help.

Matt
